### ISSUE TITLE
Hard to Identify what is Clickable on the Badge

### ISSUE THREAD

**Issue by bintsiful** [jon-dixon/badge_info_popup_tcp#1]
When clicking on the icon, it is hard to identify what is clickable on the badge since the default cursor pointer is the same. 
A change of the cursor would make it more intuitive and interactive . 
I suggest adding this for better UX

```
span.t-Badge-icon.margin-left-sm {
    cursor: pointer;
}
```

**Comment by jon-dixon** [comment]
Great idea; I appreciate the feedback. I added a new class, cn-info-badge-icon, and added the cursor: pointer to that class. This is updated in the demo app. I will release a new version of the Plugin with this change in a few days. Thank you again for the great suggestion.
